server:
  port: 8000
  servlet:
    context-path: /blog
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  config:
    import: conf/app-base.yml,conf/db.yml
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 駝峰命名
    map-underscore-to-camel-case: true
  mapper-locations: classpath:/mappers/**/*.xml